version: "3.4"
services:
  db:
    image: kartoza/postgis:12.0
    environment:
      - POSTGRES_DB=service_stac_local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_topology
    user: ${UID}
    ports:
      - 15432:5432
    volumes:
      - type: bind
        source: ${PWD}/.volumes/postgresql
        target: /var/lib/postgresql
  s3:
    image: minio/minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      # - MINIO_USERNAME=$(id -u)
      # - MINIO_GROUPNAME=$(id -g)
    user: ${UID}
    command: server /data
    volumes:
      - type: bind
        source: ${PWD}/.volumes/minio
        target: /data
    ports:
      - 9090:9000
