version: "2"
services:
  app:
    image: swisstopo/service-stac:local
    ports:
      - "${HTTP_PORT}:8080"
    environment:
      - DEBUG=1
      - LOGGING_CFG
      - DB_USER
      - DB_PW
      - DB_HOST
