version: "3.4"
services:
  db:
    image: kartoza/postgis:12.0
    environment:
      - POSTGRES_DB=service_stac
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_topology
  app:
    build:
      context: .
      target: test
    image: swisstopo/service-stac:latest-dev
    # spinning up postgis container takes some time, app needs to wait
    # for it to be ready before connecting
    # see: https://docs.docker.com/compose/startup-order/
    entrypoint: ["/app/wait-for-it.sh", "db:5432", "--", "python3", "manage.py"]
    command: test --verbosity=2
    depends_on:
      - db
    environment:
      - DEBUG=True
      - LOGGING_CFG=/app/config/logging-cfg-local.yml
      - DB_USER=postgres
      - DB_PW=postgres
      - DB_NAME=service_stac
      - DB_HOST=db
      - APP_ENV=ci
      - TEST_ENABLE_LOGGING=1
