openapi: 3.0.1
info:
  contact:
    name: API Specification (based on STAC)
    url: http://data.geo.admin.ch/api/stac/v0.9/
  description: >-
    This is an OpenAPI definition of the API to query and access federal geodata on
    data.geo.admin.ch. The API is based on the core SpatioTemporal Asset Catalog API specification
    [STAC](http://stacspec.org) and adds two extensions for extended searching possibilities.


    **Note:** The API is _not_ productively accessible yet, this is a preliminary outlook of how it
    will look like. Minor changes are possible and will be reflected in this document.
  title: The SpatioTemporal Asset Catalog API for data.geo.admin.ch
  version: 0.9.0
servers:
  - description: Data.geo.admin.ch
    url: http://data.geo.admin.ch/api/stac/v0.9
tags:
  - description: Essential characteristics of this API
    name: Capabilities
  - description: Access to data (features)
    name: Data
  - description: Extension to OGC API - Features to support STAC metadata model and search API
    name: STAC
  - description: >-
      All write requests require authentication. There are several options for a user to
      authenticate himself:

      * When using the browsable API the user can simply use the admin interface for logging in

      * Using basic authentication for the write requests.

      * Using token authentication for the write requests. See description of the get-token POST endpoint
      at the bottom on how to obtain a token (requires that user already exists and knows his password).
    name: Data Management
